name: snakemake-tutorial
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - snakemake-minimal[version='>=9.7.1']
  - jinja2
  - matplotlib
  - graphviz
  - samtools[version='>=1.19']
  - pygments
  - pysam=0.22
  - biopython
  - numpy
  - networkx
  - revbayes
  - pandas
  - seaborn
  - kneed
  - ipykernel
  - tqdm
  - mafft
  - iqtree
  - raxml-ng
  - hmmer
  - prodigal
  - ete3
  - pytorch
  - threadpoolctl
  - pytest
  - cython
  - clustalo
  - rpy2
  - mash
  - fasttree
  - phylophlan
  - anytree
  - pygraphviz
  - python-graphviz
  - matplotlib-venn
  - scikit-learn
