#!/usr/bin/env python3
"""
Compute precision-recall curve for a chosen virion model (default: model4) using virion_sets_named.json mapping.

Behaviour mirrors ensemble_pr_curve.py except the ground-truth sets are taken from the specified model key in the JSON (e.g. 'model4').

Outputs:
- CSV: model4_pr_curve.csv (thresh, precision, recall, TP, FP, FN, TN, n_predicted, n_ground_pos)
- PNG: model4_precision_recall.png
"""
import argparse
import json
import os
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


def load_json_sets(json_path: str, model_key: str):
    with open(json_path, 'r') as f:
        data = json.load(f)
    if model_key not in data:
        raise KeyError(f"JSON must contain top-level key '{model_key}'")
    mdl = data[model_key]

    def norm_list(l):
        return [s.strip().lower() for s in l]

    true = set(norm_list(mdl.get('true', [])))
    negative = set(norm_list(mdl.get('negative', [])))
    suspected = set(norm_list(mdl.get('suspected', [])))
    unlikely = set(norm_list(mdl.get('unlikely', [])))

    ground_pos = true.union(negative)
    ground_neg = suspected.union(unlikely)
    model_hosts = true.union(negative).union(suspected).union(unlikely)

    return {
        'true': true,
        'negative': negative,
        'suspected': suspected,
        'unlikely': unlikely,
        'ground_pos': ground_pos,
        'ground_neg': ground_neg,
        'model_hosts': model_hosts,
    }


def compute_pr_curve(df: pd.DataFrame, score_col: str, host_col: str, sets: dict, thresholds: np.ndarray):
    # normalize and select rows that match any host in the model sets
    df = df.copy()
    df['__host_norm'] = df[host_col].astype(str).str.strip().str.lower()

    present_mask = df['__host_norm'].isin(sets['model_hosts'])
    df_present = df.loc[present_mask].reset_index(drop=True)

    # scores/hosts for those present in the CSV
    scores_present = pd.to_numeric(df_present[score_col], errors='coerce').values
    hosts_present = df_present['__host_norm'].values

    # find model hosts missing from the CSV and treat them as always-predicted-negative
    missing_hosts = sorted(list(sets['model_hosts'] - set(hosts_present)))
    if missing_hosts:
        # scores for missing hosts are NaN so comparisons yield False -> always negative
        scores_missing = np.array([np.nan] * len(missing_hosts), dtype=float)
        hosts_missing = np.array(missing_hosts, dtype=object)
        scores = np.concatenate([scores_present, scores_missing])
        hosts = np.concatenate([hosts_present, hosts_missing])
        print(f"Note: {len(missing_hosts)} model host(s) not found in CSV; treating as predicted-negative for all thresholds.")
    else:
        scores = scores_present
        hosts = hosts_present

    rows = []
    # membership masks now include missing hosts
    is_ground_pos = np.array([h in sets['ground_pos'] for h in hosts])
    is_ground_neg = np.array([h in sets['ground_neg'] for h in hosts])

    for t in thresholds:
        # ensure NaN scores are treated as not predicted positive
        pred_pos = (~np.isnan(scores)) & (scores < float(t))
        TP = int(((pred_pos) & (is_ground_pos)).sum())
        FP = int(((pred_pos) & (is_ground_neg)).sum())
        FN = int(((~pred_pos) & (is_ground_pos)).sum())
        TN = int(((~pred_pos) & (is_ground_neg)).sum())
        n_pred = int(pred_pos.sum())
        n_ground_pos = int(is_ground_pos.sum())

        precision = TP / (TP + FP) if (TP + FP) > 0 else 0.0
        recall = TP / (TP + FN) if (TP + FN) > 0 else 0.0

        rows.append({
            'thresh': float(t),
            'precision': float(precision),
            'recall': float(recall),
            'TP': TP,
            'FP': FP,
            'FN': FN,
            'TN': TN,
            'n_predicted': n_pred,
            'n_ground_pos': n_ground_pos,
        })

    return pd.DataFrame(rows)


def plot_pr(df_pr: pd.DataFrame, outpath: str):
    plt.figure(figsize=(7,6))
    plt.plot(df_pr['recall'], df_pr['precision'], lw=1.5, color='blue')
    plt.scatter(df_pr['recall'], df_pr['precision'], s=8, alpha=0.5)
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.title('Model PR curve')
    plt.grid(True, alpha=0.3)
    plt.xlim(0,1)
    plt.ylim(0,1)
    plt.tight_layout()
    plt.savefig(outpath, dpi=300)
    print('Saved PR plot to', outpath)
    plt.close()


def main():
    p = argparse.ArgumentParser()
    # prefer hybrid_model.csv (generated by hybrid_print) if present in Fresnel project
    default_csv = '../Fresnel/Fresnel/hybrid_model.csv'
    p.add_argument('--csv', default=default_csv, help='CSV with host and score columns')
    p.add_argument('--json', default='virion_sets_named.json', help='JSON with model truth sets')
    p.add_argument('--model', default='model4', help='Model key in JSON to use for ground truth (default: model4)')
    p.add_argument('--host-col', default='Sp', help='Column name for species/host names in CSV')
    # hybrid_print writes R.Stock1_prop which uses the '< threshold' logic; default to that when present
    default_score = 'R.Stock1_prop'
    p.add_argument('--score-col', default=default_score, help='Column name for numeric score')
    p.add_argument('--out-csv', default='model4_pr_curve.csv')
    p.add_argument('--out-plot', default='model4_precision_recall.png')
    # use the hybrid threshold grid by default: np.arange(0,1002)/1000
    p.add_argument('--threshold-step', type=float, default=None, help='Step for thresholds; if not set will use hybrid grid 0..1 step 0.001 (inclusive)')
    args = p.parse_args()

    csv_path = Path(args.csv)
    json_path = Path(args.json)

    if not csv_path.exists():
        raise SystemExit(f'CSV not found: {csv_path}')
    if not json_path.exists():
        raise SystemExit(f'JSON not found: {json_path}')

    df = pd.read_csv(csv_path, dtype=str).fillna('')
    if args.host_col not in df.columns:
        raise SystemExit(f"Host column '{args.host_col}' not found in CSV columns: {list(df.columns)}")
    if args.score_col not in df.columns:
        raise SystemExit(f"Score column '{args.score_col}' not found in CSV columns: {list(df.columns)}")

    sets = load_json_sets(str(json_path), args.model)

    if args.threshold_step is None:
        thresholds = np.arange(0, 1002) / 1000.0
    else:
        thresholds = np.arange(0, 1.0 + args.threshold_step/2, args.threshold_step)

    df_pr = compute_pr_curve(df, score_col=args.score_col, host_col=args.host_col, sets=sets, thresholds=thresholds)

    df_pr.to_csv(args.out_csv, index=False)
    print('Saved PR CSV to', args.out_csv)

    plot_pr(df_pr, args.out_plot)

    # best F1
    f1 = (2 * df_pr['precision'] * df_pr['recall']) / (df_pr['precision'] + df_pr['recall']).replace({0: np.nan})
    best_idx = f1.idxmax()
    if pd.notna(best_idx):
        print('\nBest threshold by F1:')
        print(df_pr.loc[int(best_idx)].to_dict())


if __name__ == '__main__':
    main()
